POST http://127.0.0.1:8070/api/v1/generator/all
Accept: application/x-ndjson
Content-Type: application/json

{
    "outputDir": "/Users/pcoundia/projects/spring-microservices-starter/products-command/src/main/java/com/generated/sales",
    "definition": {
      "name": "Sale",
      "fields": [
        { "name": "id", "type": "String" },
        { "name": "name", "type": "String" },
        { "name": "amount", "type": "Double" }
      ]
    }
  }

###

