name: pcoundia
services:
  app:
    image: pcoundia
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/pcoundia
#    ports:
#      - 127.0.0.1:8080:8080
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql

  rabbitmq:
    extends:
      file: ./rabbitmq.yml
      service: rabbitmq

