version: '3.8'

name: pcoundia

services:
  rabbitmq:
    container_name: pcoundia-rabbitmq
    image: rabbitmq:3-management
#    networks:
#      - pcoundia-network
    environment:
      RABBITMQ_DEFAULT_USER: pcoundia
      RABBITMQ_DEFAULT_PASS: pcoundia
    #      RABBITMQ_DEFAULT_VHOST: pcoundia
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ protocol
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5

#volumes:
#  rabbitmq_data:
#    driver: local
