version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: pcoundia-selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    platform: linux/amd64  # ✅ Force l'archi x86 pour Mac M1

  chrome:
    image: selenium/node-chrome:latest
    container_name: pcoundia-node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g  # ✅ Évite les crashs mémoire de Chrome
    platform: linux/amd64  # ✅ Force l'archi x86 pour Mac M1
